### ISSUE TITLE
Upgrade extract.py for python3

### ISSUE THREAD

**Issue by NorthDecoder** [NorthDecoder/nasaMining#14]
- [ ] change print to include ( )
- [ ] add a requirements.txt file for required python packages for the project
- [ ] add installation notes for usage of the requirements.txt; ie `pip install -r requirements.txt`

**Comment by NorthDecoder** [comment]
The dependency prerequisites are defined in the 'requirements.txt 'file.  Pay attention to the definition order.

**Comment by NorthDecoder** [comment]
Commit 9f5aef1 resolves the requirements.txt item
Commit 22b43d7 resolves the print item in extract.py
